agents:
  container_image: ubuntu-2004-ci

steps:
  - label: ":shipit: Build"
    key: build
    commands:
      - ./scripts/cibuild build
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - label: "Run Tests"
    key: test
    depends_on: build
    commands:
      - ./scripts/cibuild test
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - label: "Parse and upload CHANGELOG"
    key: "parse-and-upload-changelog"
    commands:
      - ./scripts/cibuild changelog
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - trigger: gm-docs-changelog-update
    depends_on: "parse-and-upload-changelog"
    label: "Update greymatter-core CHANGELOG in gm-docs"
    branches: "main"
    build:
      meta_data:
        # The destination filename in gm-docs /data/changelogs
        changelog_filename: "greymatter-core.toml"
    async: true

  - label: "Generate manifests"
    key: "generate-manifests"
    agents:
      container_image: ubuntu-2204-ci
      queue: default
    depends_on: 
      - build
      - test
    commands:
      - mkdir generated-manifests-cue-output/
      - mkdir transform-manifest/
      - mkdir generated-manifests/

      - cue eval -c ./k8s/outputs -e operator_manifests_yaml --out=text > generated-manifests-cue-output/operator.yaml
      - sed -i 's/git@github.com:greymatter-io\/greymatter-core.git/git@github.com:<your-org>\/greymatter-core.git/g' generated-manifests-cue-output/operator.yaml
      - mv generated-manifests-cue-output/operator.yaml transform-manifest/manifest.yaml
      - ./scripts/reorder-manifest.py
      - if [[ $(cat transform-manifest/manifest-reorder.yaml | tail -1) == "---" ]]; then echo "Not All k8s resources were added to manifest during reorder" && exit 2; fi
      - mv transform-manifest/manifest-reorder.yaml generated-manifests/operator.yaml
      
      - cue eval -c ./k8s/outputs -e operator_manifests_yaml --out=text -t spire=true > generated-manifests-cue-output/operator-spire.yaml
      - sed -i 's/git@github.com:greymatter-io\/greymatter-core.git/git@github.com:<your-org>\/greymatter-core.git/g' generated-manifests-cue-output/operator-spire.yaml
      - mv generated-manifests-cue-output/operator-spire.yaml transform-manifest/manifest.yaml
      - ./scripts/reorder-manifest.py
      - if [[ $(cat transform-manifest/manifest-reorder.yaml | tail -1) == "---" ]]; then echo "Not All k8s resources were added to manifest during reorder" && exit 2; fi
      - mv transform-manifest/manifest-reorder.yaml generated-manifests/operator-spire.yaml

      - cue eval -c ./k8s/outputs -e operator_manifests_yaml --out=text -t openshift=true > generated-manifests-cue-output/operator-openshift.yaml
      - sed -i 's/git@github.com:greymatter-io\/greymatter-core.git/git@github.com:<your-org>\/greymatter-core.git/g' generated-manifests-cue-output/operator-openshift.yaml
      - mv generated-manifests-cue-output/operator-openshift.yaml transform-manifest/manifest.yaml
      - ./scripts/reorder-manifest.py
      - if [[ $(cat transform-manifest/manifest-reorder.yaml | tail -1) == "---" ]]; then echo "Not All k8s resources were added to manifest during reorder" && exit 2; fi
      - mv transform-manifest/manifest-reorder.yaml generated-manifests/operator-openshift.yaml


      - cue eval -c ./k8s/outputs -e operator_manifests_yaml --out=text -t openshift=true -t spire=true > generated-manifests-cue-output/operator-openshift-spire.yaml
      - sed -i 's/git@github.com:greymatter-io\/greymatter-core.git/git@github.com:<your-org>\/greymatter-core.git/g' generated-manifests-cue-output/operator-openshift-spire.yaml
      - mv generated-manifests-cue-output/operator-openshift-spire.yaml transform-manifest/manifest.yaml
      - ./scripts/reorder-manifest.py
      - if [[ $(cat transform-manifest/manifest-reorder.yaml | tail -1) == "---" ]]; then echo "Not All k8s resources were added to manifest during reorder" && exit 2; fi
      - mv transform-manifest/manifest-reorder.yaml generated-manifests/operator-openshift-spire.yaml

      - rm -r generated-manifests-cue-output/
      - rm -r transform-manifest/
      - buildkite-agent artifact upload "generated-manifests/*"

  - label: "Create Tarball and push to staging"
    key: "push-to-staging"
    depends_on:
      - test
      - generate-manifests
    commands:
      - buildkite-agent artifact download generated-manifests/* . --build ${BUILDKITE_BUILD_ID} --step generate-manifests
      - ./scripts/cibuild release

  - label: "test-promote artifacts to staging"
    key: "promote-test"
    env:
      SRC_GENERIC_CI: "dev-generic"
      DEST_GENERIC_CI: "ci-staging-generic"
      SRC_OCI_CI: "dev-oci"
      DEST_OCI_CI: "ci-staging-oci"
    # promotion defaults to dry run
    command: ./scripts/promotion 

