agents:
  container_image: ubuntu-2004-ci

# promotes artifacts to their release repos
# updates greymatter-download-<version><-rc>.sh file
steps:
  - label: "promote artifacts to staging"
    key: "promote"
    env:
      SRC_GENERIC_CI: "dev-generic"
      DEST_GENERIC_CI: "ci-staging-generic"
      SRC_OCI_CI: "dev-oci"
      DEST_OCI_CI: "ci-staging-oci"
    # --yes flag for promotion results in actual promotion
    command: ./scripts/promotion --yes
    artifact_paths:
      - release-versions.yaml
      - greymatter-download*.sh
      - inputs-output.cue
