steps:
  - label: ":shipit: Build"
    key: build
    commands:
      - ./scripts/cibuild build
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - label: "Run Tests"
    key: test
    depends_on: build
    commands:
      - ./scripts/cibuild test
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - label: "Parse and upload CHANGELOG"
    key: "parse-and-upload-changelog"
    commands:
      - ./scripts/cibuild changelog
    agents:
      container_image: ubuntu-2204-ci
      queue: default

  - trigger: gm-docs-changelog-update
    depends_on: "parse-and-upload-changelog"
    label: "Update greymatter-core CHANGELOG in gm-docs"
    branches: "main"
    build:
      meta_data:
        # The destination filename in gm-docs /data/changelogs
        changelog_filename: "greymatter-core.toml"
    async: true

  - label: "Release"
    depends_on: test
    commands:
      - ./scripts/cibuild release
