agents:
  container_image: ubuntu-2004-ci
steps:
  # this is in place of automated smoke test
  - block: "I have run a smoke test using the inputs-output.cue artifact from merge to main build (under promote artifacts to staging)"

  - input: "Information please"
    key: info-request
    fields:
      - text: "What is this Release Called"
        key: "release"

  - label: "test-promote artifacts to oci/ generic"
    key: "promote-test-tag"
    depends_on:
      - info-request
    env:
      SRC_GENERIC_CI: "ci-staging-generic"
      DEST_GENERIC_CI: "generic"
      SRC_OCI_CI: "ci-staging-oci"
      DEST_OCI_CI: "oci"
    # promotion defaults to dry run
    command: ./scripts/promotion 

  # promotes artifacts to their release repos
  # TODO: validates updates greymatter-download-<version><-rc>.sh file
  - label: "promote artifacts to oci/ generic"
    key: "promote-tag"
    depends_on: 
      - promote-test-tag
      - info-request
    env:
      SRC_GENERIC_CI: "ci-staging-generic"
      DEST_GENERIC_CI: "generic"
      SRC_OCI_CI: "ci-staging-oci"
      DEST_OCI_CI: "oci"
    # --yes flag for promotion results in actual promotion
    command: ./scripts/promotion --yes
    artifact_paths:
      - release-versions.yaml
      - greymatter-download*.sh
      - inputs-output.cue

  # promote commit to tag
  - label: "Promote Tarball (tag)"
    key: promote-generic-latest
    depends_on:
      - promote-test-tag
      - info-request
    env:
      JF_SRC_REGISTRY: dev-generic
      JF_DEST_REGISTRY: generic
    commands:
      - mkdir -p ./tmp-workspace
      - jf rt download $$JF_SRC_REGISTRY/greymatter-core/greymatter-core_${BUILDKITE_COMMIT}_none_none.tar.gz --flat=true .
      - pwd && ls -al ./tmp-workspace
      - tar -xf greymatter-core_${BUILDKITE_COMMIT}_none_none.tar.gz -C ./tmp-workspace
      - pwd && ls -al ./tmp-workspace
      - sed -i 's|greymatter.jfrog.io/dev-oci/greymatter-operator:0.16.1|greymatter.jfrog.io/oci/greymatter-operator:0.16.1|g' tmp-workspace/generated-manifests-cue-output/operator.yaml
      - sed -i 's|greymatter.jfrog.io/dev-oci/greymatter-operator:0.16.1|greymatter.jfrog.io/oci/greymatter-operator:0.16.1|g' tmp-workspace/generated-manifests-cue-output/operator-spire.yaml
      - sed -i 's|greymatter.jfrog.io/dev-oci/greymatter-operator:0.16.1|greymatter.jfrog.io/oci/greymatter-operator:0.16.1|g' tmp-workspace/generated-manifests-cue-output/operator-openshift.yaml
      - sed -i 's|greymatter.jfrog.io/dev-oci/greymatter-operator:0.16.1|greymatter.jfrog.io/oci/greymatter-operator:0.16.1|g' tmp-workspace/generated-manifests-cue-output/operator-openshift-spire.yaml
      - buildkite-agent artifact download inputs-output.cue . --step promote-tag
      - mv inputs-output.cue ./tmp-workspace/inputs.cue
      - tar -cf greymatter-core_${BUILDKITE_TAG:1}_none_none.tar.gz ./tmp-workspace
      - jf rt upload greymatter-core_${BUILDKITE_TAG:1}_none_none.tar.gz $$JF_SRC_REGISTRY/greymatter-core/greymatter-core_${BUILDKITE_TAG:1}_none_none.tar.gz
