agents:
  container_image: ubuntu-2004-ci
steps:
  # this is in place of automated smoke test
  - block: "I have run a smoke test using the inputs-output.cue artifact from merge to main build (under promote artifacts to staging)"

  - input: "Information please"
    key: info-request
    fields:
      - text: "What is this Release Called"
        key: "release"

  - label: "test-promote artifacts to oci/ generic"
    key: "promote-test-tag"
    depends_on:
      - info-request
    env:
      SRC_GENERIC_CI: "ci-staging-generic"
      DEST_GENERIC_CI: "generic"
      SRC_OCI_CI: "ci-staging-oci"
      DEST_OCI_CI: "oci"
    # promotion defaults to dry run
    command: ./scripts/promotion 

  # promotes artifacts to their release repos
  # TODO: validates updates greymatter-download-<version><-rc>.sh file
  - label: "promote artifacts to oci/ generic"
    key: "promote-tag"
    depends_on: 
      - promote-test-tag
      - info-request
    env:
      SRC_GENERIC_CI: "ci-staging-generic"
      DEST_GENERIC_CI: "generic"
      SRC_OCI_CI: "ci-staging-oci"
      DEST_OCI_CI: "oci"
    # --yes flag for promotion results in actual promotion
    command: ./scripts/promotion --yes
    # eventually we will want to automatically push greymatter-download*.sh to artifactory
    artifact_paths:
      - release-versions.yaml
      - greymatter-download*.sh
      - inputs-output.cue

  # promote commit to tag
  - label: "Promote Tarball to staging (tag)"
    key: promote-generic-latest
    depends_on:
      - promote-test-tag
      - info-request
    env:
      JF_SRC_REGISTRY: dev-generic
      JF_DEST_REGISTRY: generic
    commands:
      - jf rt cp $$JF_SRC_REGISTRY/greymatter-core/greymatter-core_${BUILDKITE_COMMIT}_none_none.tar.gz $$JF_DEST_REGISTRY/greymatter-core/greymatter-core_${BUILDKITE_TAG:1}_none_none.tar.gz --fail-no-op=true --flat=true