#!/bin/bash

set -e

for dependency in go cue staticcheck git
do
    if ! which $dependency &> /dev/null; then
        echo "$dependency is missing from your \$PATH"
        exit 1
    elif [ "$dependency" == "go" ]; then
        go mod tidy
        go mod vendor
    elif [ "$dependency" == "cue" ]; then
        (cd ./pkg/cuemodule/cue.mod; cue get go github.com/greymatter-io/common/api/...; cue get go k8s.io/api/...)
    elif [ "$dependency" == "git" ]; then
        git submodule update --init --recursive --remote
    fi
done
