#!/bin/bash

set -e

for dependency in git pip3 pytest
do
  if ! which $dependency &> /dev/null; then
    echo "$dependency is missing from your \$PATH"
    exit 1
  elif [ "$dependency" == "git" ]; then
    git submodule update --init --recursive
  fi
done
