#!/bin/bash

set -e

#### Commands

# Parse CHANGELOG into structured data suitable for powering templates
# on our documentation site.
cmd_changelog() {
  export changelog_toml="/tmp/changelog.toml"
  parse-changelog CHANGELOG.md $changelog_toml
  buildkite-agent artifact upload $changelog_toml
}

# There isn't a build per se. We just need to make sure that we have
# greymatter-cue submodule on disk.
cmd_build() {
  ./scripts/bootstrap

  # always push latest tarball when merging to main
  if [[ "$BUILDKITE_BRANCH" == "main" ]]; then
    release_bundle
  fi
}

# Install the greymatter-cue and run 'cue eval' tests.
cmd_test() {
  ./scripts/bootstrap
  ./scripts/test eval_all
}

if [ $# -eq 0 ]; then
  echo "missing argument"
  exit 1
fi

CMD=$1
shift
case $CMD in
  build|changelog|test)
    cmd_$CMD "$@"
    ;;
  *)
    echo "invalid argument: $CMD"
    exit 1
    ;;
esac
